import { useState } from 'react';
import { motion } from 'framer-motion';
import { Download, FileText, Printer, Share2 } from 'lucide-react';
import { GlassPanel } from '@/components/common/GlassPanel';
import { Badge } from '@/components/common/Badge';
import { Button } from '@/components/common/Button';
import { MISSION_ID, MISSION_NAME, LANDING_SITES } from '@/data/missionData';
import { cn } from '@/utils/cn';
import { staggerContainer, fadeUp } from '@/utils/motion';

const reportSections = [
  { id: 'exec', title: 'Executive Summary', pages: 2, status: 'ready' as const },
  { id: 'sar', title: 'SAR Processing Report', pages: 8, status: 'ready' as const },
  { id: 'ice', title: 'Ice Detection Analysis', pages: 12, status: 'ready' as const },
  { id: 'sites', title: 'Landing Site Assessment', pages: 6, status: 'ready' as const },
  { id: 'sim', title: 'Rover Simulation Data', pages: 4, status: 'generating' as const },
  { id: 'appendix', title: 'Technical Appendix', pages: 14, status: 'ready' as const },
];

export function ReportsWorkspace() {
  const [selected, setSelected] = useState(reportSections[0].id);
  const [exporting, setExporting] = useState(false);

  const handleExport = () => {
    setExporting(true);
    setTimeout(() => setExporting(false), 2000);
  };

  const primary = LANDING_SITES[0];

  return (
    <motion.div
      variants={staggerContainer}
      initial="hidden"
      animate="visible"
      className="flex h-full min-h-0 flex-col gap-4"
    >
      <motion.div variants={fadeUp} className="flex flex-wrap items-start justify-between gap-3">
        <div>
          <Badge color="ice">Report Generator</Badge>
          <h2 className="mt-2 font-display text-xl font-bold text-text-primary">Reports</h2>
          <p className="text-sm text-text-secondary">
            Exportable mission summaries · ISRO standard format
          </p>
        </div>
        <div className="flex gap-2">
          <Button variant="secondary" size="sm" onClick={handleExport} disabled={exporting}>
            <Download className="size-3.5" />
            {exporting ? 'Generating...' : 'Export PDF'}
          </Button>
          <Button variant="ghost" size="sm">
            <Share2 className="size-3.5" />
            Share
          </Button>
        </div>
      </motion.div>

      <div className="grid min-h-0 flex-1 gap-4 lg:grid-cols-[280px_1fr]">
        <motion.div variants={fadeUp}>
          <GlassPanel animate={false} className="flex h-full flex-col p-3">
            <h3 className="mb-3 px-1 text-xs font-semibold uppercase tracking-widest text-text-muted">
              Sections
            </h3>
            <ul className="space-y-1">
              {reportSections.map((section) => (
                <li key={section.id}>
                  <button
                    type="button"
                    onClick={() => setSelected(section.id)}
                    className={cn(
                      'flex w-full items-center gap-2 rounded-lg px-3 py-2 text-left transition-all',
                      selected === section.id
                        ? 'bg-ice/10 text-ice'
                        : 'text-text-secondary hover:bg-white/4 hover:text-text-primary',
                    )}
                  >
                    <FileText className="size-3.5 shrink-0" />
                    <div className="min-w-0 flex-1">
                      <p className="truncate text-xs font-medium">{section.title}</p>
                      <p className="text-[10px] text-text-muted">{section.pages} pages</p>
                    </div>
                    <Badge color={section.status === 'ready' ? 'signal' : 'warning'}>
                      {section.status}
                    </Badge>
                  </button>
                </li>
              ))}
            </ul>
          </GlassPanel>
        </motion.div>

        <motion.div variants={fadeUp}>
          <GlassPanel animate={false} className="flex h-full flex-col p-6">
            <div className="mb-6 flex items-start justify-between border-b border-border-subtle pb-4">
              <div>
                <p className="font-mono text-[10px] text-text-muted">{MISSION_ID}</p>
                <h3 className="mt-1 font-display text-lg font-bold text-text-primary">
                  {MISSION_NAME}
                </h3>
                <p className="mt-1 text-xs text-text-secondary">
                  Generated by PROJECT CABEUS · ISRO Mission Control
                </p>
              </div>
              <div className="flex size-12 items-center justify-center rounded-lg border border-isro-saffron/30 bg-gradient-to-br from-isro-saffron/10 to-isro-green/10">
                <span className="font-mono text-[8px] font-bold leading-tight text-center text-text-primary">
                  ISRO
                </span>
              </div>
            </div>

            <div className="min-h-0 flex-1 space-y-4 overflow-y-auto text-sm leading-relaxed text-text-secondary">
              <section>
                <h4 className="mb-2 font-semibold text-text-primary">Mission Overview</h4>
                <p>
                  Chandrayaan-2 DFSAR dual-frequency SAR data from the lunar south polar region
                  has been processed through the CABEUS ice intelligence pipeline. Analysis
                  covers {847} km² of terrain between 70°S and 90°S latitude.
                </p>
              </section>

              <section>
                <h4 className="mb-2 font-semibold text-text-primary">Primary Finding</h4>
                <p>
                  Subsurface ice signatures detected at {primary.name} with{' '}
                  {primary.iceProbability}% probability. Composite landing score of{' '}
                  {primary.score}/100 recommends this site as primary target for future
                  resource extraction missions.
                </p>
              </section>

              <section>
                <h4 className="mb-2 font-semibold text-text-primary">Site Rankings</h4>
                <div className="overflow-hidden rounded-lg border border-border-subtle">
                  <table className="w-full text-xs">
                    <thead>
                      <tr className="border-b border-border-subtle bg-white/4">
                        <th className="px-3 py-2 text-left font-medium text-text-muted">Site</th>
                        <th className="px-3 py-2 text-right font-medium text-text-muted">Score</th>
                        <th className="px-3 py-2 text-right font-medium text-text-muted">Ice %</th>
                      </tr>
                    </thead>
                    <tbody>
                      {LANDING_SITES.map((site) => (
                        <tr key={site.id} className="border-b border-border-subtle last:border-0">
                          <td className="px-3 py-2 text-text-primary">{site.name}</td>
                          <td className="px-3 py-2 text-right font-mono text-ice">{site.score}</td>
                          <td className="px-3 py-2 text-right font-mono text-mission">
                            {site.iceProbability}%
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </section>
            </div>

            <div className="mt-4 flex gap-2 border-t border-border-subtle pt-4">
              <Button variant="secondary" size="sm">
                <Printer className="size-3.5" />
                Print Preview
              </Button>
              <p className="ml-auto self-center font-mono text-[10px] text-text-muted">
                46 pages · Last updated T+847 min
              </p>
            </div>
          </GlassPanel>
        </motion.div>
      </div>
    </motion.div>
  );
}
