import { motion } from 'framer-motion';
import { Download, FileText, Printer, Share2 } from 'lucide-react';
import { GlassPanel } from '@/components/common/GlassPanel';
import { Badge } from '@/components/common/Badge';
import { Button } from '@/components/common/Button';
import {
  ReportSectionPreview,
  useMissionReport,
} from '@/features/reports';
import { cn } from '@/utils/cn';
import { staggerContainer, fadeUp } from '@/utils/motion';

export function ReportsWorkspace() {
  const {
    data,
    sections,
    selectedSection,
    setSelectedSection,
    exporting,
    exportPdf,
    printPreview,
  } = useMissionReport();

  const activeSection = sections.find((s) => s.id === selectedSection)!;

  return (
    <motion.div
      variants={staggerContainer}
      initial="hidden"
      animate="visible"
      className="flex h-full min-h-0 flex-col gap-4"
    >
      <motion.div variants={fadeUp} className="flex flex-wrap items-start justify-between gap-3">
        <div>
          <Badge color="ice">Report Generator</Badge>
          <h2 className="mt-2 font-display text-xl font-bold text-text-primary">Mission Report</h2>
          <p className="text-sm text-text-secondary">
            Professional PDF export · ISRO standard format · 12 pages
          </p>
        </div>
        <div className="flex gap-2">
          <Button variant="secondary" size="sm" onClick={exportPdf} disabled={exporting}>
            <Download className="size-3.5" />
            {exporting ? 'Generating PDF…' : 'Export PDF'}
          </Button>
          <Button variant="ghost" size="sm">
            <Share2 className="size-3.5" />
            Share
          </Button>
        </div>
      </motion.div>

      <div className="grid min-h-0 flex-1 gap-4 lg:grid-cols-[280px_1fr]">
        <motion.div variants={fadeUp}>
          <GlassPanel animate={false} className="flex h-full flex-col p-3">
            <h3 className="mb-3 px-1 text-xs font-semibold uppercase tracking-widest text-text-muted">
              Sections
            </h3>
            <ul className="space-y-1">
              {sections.map((section) => (
                <li key={section.id}>
                  <button
                    type="button"
                    onClick={() => setSelectedSection(section.id)}
                    className={cn(
                      'flex w-full items-center gap-2 rounded-lg px-3 py-2 text-left transition-all',
                      selectedSection === section.id
                        ? 'bg-ice/10 text-ice'
                        : 'text-text-secondary hover:bg-white/4 hover:text-text-primary',
                    )}
                  >
                    <FileText className="size-3.5 shrink-0" />
                    <div className="min-w-0 flex-1">
                      <p className="truncate text-xs font-medium">{section.title}</p>
                      <p className="text-[10px] text-text-muted">{section.pages} page{section.pages > 1 ? 's' : ''}</p>
                    </div>
                    <Badge color={section.status === 'ready' ? 'signal' : 'warning'}>
                      {section.status}
                    </Badge>
                  </button>
                </li>
              ))}
            </ul>
          </GlassPanel>
        </motion.div>

        <motion.div variants={fadeUp}>
          <GlassPanel animate={false} className="flex h-full flex-col p-6">
            <div className="mb-6 flex items-start justify-between border-b border-border-subtle pb-4">
              <div>
                <p className="font-mono text-[10px] text-text-muted">{data.meta.missionId}</p>
                <h3 className="mt-1 font-display text-lg font-bold text-text-primary">
                  {data.meta.missionName}
                </h3>
                <p className="mt-1 text-xs text-text-secondary">
                  {activeSection.title} · Generated by PROJECT CABEUS
                </p>
              </div>
              <div className="flex size-12 items-center justify-center rounded-lg border border-isro-saffron/30 bg-gradient-to-br from-isro-saffron/10 to-isro-green/10">
                <span className="text-center font-mono text-[8px] font-bold leading-tight text-text-primary">
                  ISRO
                </span>
              </div>
            </div>

            <div className="min-h-0 flex-1 overflow-y-auto">
              <ReportSectionPreview data={data} section={selectedSection} />
            </div>

            <div className="mt-4 flex gap-2 border-t border-border-subtle pt-4">
              <Button variant="secondary" size="sm" onClick={printPreview}>
                <Printer className="size-3.5" />
                Print Preview
              </Button>
              <Button variant="secondary" size="sm" onClick={exportPdf} disabled={exporting}>
                <Download className="size-3.5" />
                {exporting ? 'Generating…' : 'Download PDF'}
              </Button>
              <p className="ml-auto self-center font-mono text-[10px] text-text-muted">
                {data.meta.totalPages} pages · {new Date(data.meta.generatedAt).toLocaleString()}
              </p>
            </div>
          </GlassPanel>
        </motion.div>
      </div>
    </motion.div>
  );
}
